### ISSUE TITLE
не понятно как добавить стратегию в конфиг.

### ISSUE THREAD

**Issue by MeMaSyT** [Sergeydigl3/zapret-discord-youtube-linux#2]
К примеру:
strategy=./general (МГТС).bat
Выдаёт ошибку:
conf.env: строка 1: синтаксическая ошибка рядом с неожиданным маркером «(»
conf.env: строка 1: `strategy=./general (МГТС).bat'
Ошибка: Отсутствуют обязательные параметры в конфигурационном файле

Пробовал прописывать без пробела и другими способами

**Comment by melvuze** [comment]
Оберни ./general (МГТС).bat в кавычки.
Должно получиться так:
`strategy='./general (МГТС).bat'`
