### ISSUE TITLE
если запускать программу самому, то она работает. Через службу не работает

### ISSUE THREAD

**Issue by MeMaSyT** [Sergeydigl3/zapret-discord-youtube-linux#3]

**Comment by KiaraNyasha** [comment]
Тоже не работало, долго ломал голову но нашёл.
Проверь conf.env, у меня там почему то неправильный сетевой интерфейс прописало. Когда запускал сам, оно спрашивало и я выбирал интерфейс eno1. Однако в конфиге conf.env был другой интерфейс. Поправил ручками, переустановил сервис - заработало.

**Comment by KiaraNyasha** [comment]
> _No description provided._

Тоже не работало, долго ломал голову но нашёл.
Проверь conf.env, у меня там почему то неправильный сетевой интерфейс прописало. Когда запускал сам, оно спрашивало и я выбирал интерфейс eno1. Однако в конфиге conf.env был другой интерфейс. Поправил ручками, переустановил сервис - заработало.

**Comment by Sergeydigl3** [comment]
conf.env сам не заполняется. Ожидается что вы сами пропишите туда все необходимое. 
(Поясняю для будущих пользователей)
